---
resources:
- name: git-interne
  type: git
  source:
    username: {{git-user}}
    password: {{git-password}}
    uri: https://github.com/jjmarc/N4P_CF.git

jobs: 
- name: manifest-generation
  public: false
  plan: 
  - get: git-interne
    trigger: true
  - task: secret-gen
    file: git-interne/concourse/task-secret-gen.yml
